**Data Preprocessing**

Importing the Libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
#Numpy Library contains mathematical tools.
#Matplotlib Library is used for ploting charts and graphs.
#Pandas Library is used for importing and managing Data.

**--------------------------------------------------------------------------------------------------------------------------------------------------------------------------**

Importing the dataset

In [2]:
dataset = pd.read_csv('C:\\Users\\Samir\\Desktop\\@ML\\Simple Regression\\DataSet\\Data.csv')

In [3]:
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [4]:
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,3:].values

In [5]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [6]:
y

array([['No'],
       ['Yes'],
       ['No'],
       ['No'],
       ['Yes'],
       ['Yes'],
       ['No'],
       ['Yes'],
       ['No'],
       ['Yes']], dtype=object)

**--------------------------------------------------------------------------------------------------------------------------------------------------------------------------**

Taking Care of Missing Data

In [7]:
from sklearn.preprocessing import Imputer    #Importing Library
#Imputer will take care of missing Datas

In [8]:
imputer =Imputer(missing_values = 'NaN',strategy = 'mean',axis = 0)

C:\Users\Samir\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:66: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


In [9]:
imputer = imputer.fit(X[:,1:3])#Imputer object is fitted to the matrix X
X[:,1:3] = imputer.transform(X[:,1:3])
#To replace the matrix X by the mean of the column

In [10]:
X


array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

**--------------------------------------------------------------------------------------------------------------------------------------------------------------------------**

**Categorical Data**


Here we can see that there are 2 datas Which can be categorised that is Country and Purchased.
Where Country contains 3 categories(France,Spain,Germany) and Purchased contain 2 categories(Yes,no).

We have to encode the text into numbers so that it is understandable by the machine

In [11]:
#Encoding Categorical Data
from sklearn.preprocessing import LabelEncoder

In [12]:
labelencoder_X = LabelEncoder()    #Calling Label Encoder Class

In [13]:
labelencoder_X.fit_transform(X[:,0])

array([0, 2, 1, 2, 1, 0, 2, 0, 1, 0])

In [14]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [15]:
X[:,0] = labelencoder_X.fit_transform(X[:,0])#fit transform function transform and fits data.

In [16]:
X

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, 63777.77777777778],
       [0, 35.0, 58000.0],
       [2, 38.77777777777778, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

We will be using dummy variables i.e. making the same number of columns as no of categories. This is done because if the country are numbered 1,2,3 etc. machine can make unwanted comparison.for example here we don't need to make comparison between the countries.So it is done when there is no need of any comparisons or where orders(like small,medium,large) does not matters.
If a certain country is present in that column that categorical column will show 1 else 0.
LabelEncoder -> encodes values without bothering for order.This creates a binary column for each category

#Making Dummy Variable

In [17]:
from sklearn.preprocessing import OneHotEncoder

In [18]:
onehotencoder = OneHotEncoder(categorical_features=[0])

In [19]:
X = onehotencoder.fit_transform(X).toarray()

C:\Users\Samir\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\Samir\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [20]:
X

array([[1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.40000000e+01,
        7.20000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 2.70000000e+01,
        4.80000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 3.00000000e+01,
        5.40000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.80000000e+01,
        6.10000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 4.00000000e+01,
        6.37777778e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.50000000e+01,
        5.80000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.87777778e+01,
        5.20000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.80000000e+01,
        7.90000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 5.00000000e+01,
        8.30000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.70000000e+01,
        6.70000000e+04]])

For variable y we don't need to use OneHotEncoder instead we can use LabelEncoder because Y is the dependent variable, and machine learning model will know that it is a category and that there is no order between the two.

In [21]:
labelencoder_y = LabelEncoder()

In [22]:
y = labelencoder_y.fit_transform(y)

C:\Users\Samir\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [23]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

**--------------------------------------------------------------------------------------------------------------------------------------------------------------------------**

**Splitting the Dataset into the Training Set and Test Set**

In [24]:
from sklearn.model_selection import train_test_split

In [25]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 0)#(X,y) is the whole array

In [26]:
X_train

array([[0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 4.00000000e+01,
        6.37777778e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.70000000e+01,
        6.70000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 2.70000000e+01,
        4.80000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.87777778e+01,
        5.20000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.80000000e+01,
        7.90000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.80000000e+01,
        6.10000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.40000000e+01,
        7.20000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.50000000e+01,
        5.80000000e+04]])

In [27]:
print('Size of Train and Test Set\nX_train = ',len(X_train),'\nX_test = ',len(X_test),'\ny_train = ',len(y_train),'\ny_test = ',len(y_test))

Size of Train and Test Set
X_train =  8 
X_test =  2 
y_train =  8 
y_test =  2


**--------------------------------------------------------------------------------------------------------------------------------------------------------------------------**

**Feature Scaling**

In [30]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()

In [31]:
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

While applying Standard Scaler object to our training set we have to first fit the object of the training sets and then transform it.while for **Test Set** We just have to transform the test set.

In [32]:
X_train

array([[-1.        ,  2.64575131, -0.77459667,  0.26306757,  0.12381479],
       [ 1.        , -0.37796447, -0.77459667, -0.25350148,  0.46175632],
       [-1.        , -0.37796447,  1.29099445, -1.97539832, -1.53093341],
       [-1.        , -0.37796447,  1.29099445,  0.05261351, -1.11141978],
       [ 1.        , -0.37796447, -0.77459667,  1.64058505,  1.7202972 ],
       [-1.        , -0.37796447,  1.29099445, -0.0813118 , -0.16751412],
       [ 1.        , -0.37796447, -0.77459667,  0.95182631,  0.98614835],
       [ 1.        , -0.37796447, -0.77459667, -0.59788085, -0.48214934]])

In [33]:
X_test

array([[-1.        ,  2.64575131, -0.77459667, -1.45882927, -0.90166297],
       [-1.        ,  2.64575131, -0.77459667,  1.98496442,  2.13981082]])